# TODO: 'snapcraft register <name>'
name: protonvpn
icon: snap/gui/protonvpn.svg
# TODO: Update summary and description 
summary: Single-line elevator pitch for your amazing snap
version: 4.4.2
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

website: https://protonvpn.com
contact: https://github.com/pedro-avalos/protonvpn-snap/issues
issues: https://github.com/pedro-avalos/protonvpn-snap/issues
source-code: https://github.com/ProtonVPN/proton-vpn-gtk-app

# TODO: Use stable and strict
base: core24
grade: devel
confinement: devmode
compression: lzo

platforms:
  amd64:

# TODO: Create app
#apps:
#  proton-vpn:
#    command: usr/bin/proton-vpn
#    desktop: snap/gui/proton-vpn.desktop
#    extensions:
#      - gnome
#    plugs:
#      - desktop
#      - desktop-legacy
#      - wayland
#      - unity7
#      - x11
#      - network
#      - network-bind

parts:
  protonvpn:
    plugin: python
    source-type: git
    source: https://github.com/ProtonVPN/proton-vpn-gtk-app
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    source-submodules: []
    override-build: |
      pip config set global.index-url https://gitlab.protontech.ch/api/v4/groups/777/-/packages/pypi/simple
      craftctl default
