# TODO: 'snapcraft register <name>'
name: protonvpn
icon: snap/gui/protonvpn.svg
title: Proton VPN
# TODO: Update summary and description 
summary: Single-line elevator pitch for your amazing snap
version: 4.4.2
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

website: https://protonvpn.com
contact: https://github.com/pedro-avalos/protonvpn-snap/issues
issues: https://github.com/pedro-avalos/protonvpn-snap/issues
source-code: https://github.com/ProtonVPN/proton-vpn-gtk-app

# TODO: Use stable and strict
base: core24
grade: devel
confinement: devmode
compression: lzo

platforms:
  amd64:

# TODO: Create app
#apps:
#  protonvpn:
#    command: usr/bin/protonvpn
#    desktop: snap/gui/protonvpn.desktop
#    extensions:
#      - gnome
#    plugs:
#      - desktop
#      - desktop-legacy
#      - wayland
#      - unity7
#      - x11
#      - network
#      - network-bind

parts:
  python-proton-core:
    plugin: python
    source-type: git
    source: https://github.com/ProtonVPN/python-proton-core.git

  python-proton-keyring-linux:
    plugin: python
    source-type: git
    source: https://github.com/ProtonVPN/python-proton-keyring-linux.git
    after:
      - python-proton-core

  python-proton-vpn-local-agent:
    plugin: python
    source-type: git
    source: https://github.com/ProtonVPN/python-proton-vpn-local-agent.git
    source-submodules: []
    after:
      - python-proton-core
      - python-proton-keyring-linux

  python-proton-vpn-api-core:
    plugin: python
    source-type: git
    source: https://github.com/ProtonVPN/python-proton-vpn-api-core.git
    source-submodules: []
    after:
      - python-proton-core
      - python-proton-keyring-linux
      - python-proton-vpn-local-agent

  python-proton-vpn-network-manager:
    plugin: python
    source-type: git
    source: https://github.com/ProtonVPN/python-proton-vpn-network-manager.git
    after:
      - python-proton-core
      - python-proton-keyring-linux
      - python-proton-vpn-local-agent
      - python-proton-vpn-api-core

  protonvpn:
    plugin: python
    source-type: git
    source: https://github.com/ProtonVPN/proton-vpn-gtk-app.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    source-submodules: []
    after:
      - python-proton-core
      - python-proton-keyring-linux
      - python-proton-vpn-local-agent
      - python-proton-vpn-api-core
      - python-proton-vpn-network-manager
