# TODO: 'snapcraft register <name>'
name: protonvpn
version: 4.9.5
icon: snap/gui/protonvpn.svg
title: Proton VPN
summary: Secures your internet and protects your online privacy
description: |
  NOTE: This app is built from Proton VPN's official open-source code, but it
  is not an official Proton app. It is not affiliated with or supported by
  Proton AG.

  Browse privately and take back control of your personal information with
  Proton VPN. Connect to one of our high-speed servers to hide your IP address,
  bypass digital borders, and stream from popular websites and platforms.

  Used by millions worldwide, our secure no-logs VPN does not record your
  browsing history, display ads, sell your data to third parties, or limit downloads.

  Proton VPN is brought to you by the CERN scientists behind Proton Mail — the
  world's largest encrypted email service.

  Free VPN features

  - Strict no-logs policy
  - Zero-access, end-to-end encryption
  - Full-disk encrypted servers
  - No bandwidth restrictions
  - Strong, secure protocols: WireGuard and OpenVPN
  - IPv6 support
  - Perfect forward secrecy: Encrypted traffic cannot be captured and
    decrypted later
  - DNS leak protection: Ensures DNS queries are never accidentally sent to
    third-party resolvers
  - Kill switch: Protects you against IP leaks caused by accidental disconnections

  Premium VPN features

  - Connect to 8500+ high speed servers across 110+ countries
  - Lightning-fast VPN speeds (up to 10 Gbps)
  - Connect up to 10 devices at the same time
  - Stream films, sports events, and videos on any streaming service (Netflix,
    Hulu, mazon Prime Video, Disney+, BBC iplayer, and more)
  - P2P (peer-to-peer) servers: Fast torrenting, gaming, and file sharing
  - Secure Core servers: Enhance your protection with double hop VPN
  - Tor servers: Connect to onion sites with your regular browser
  - NetShield Ad-blocker: Protect yourself from ads, trackers, and malware on
    websites and pps
  - VPN Accelerator: Unique technology increases VPN speeds by up to 400%

  Why Proton VPN?

  - No personal data required to sign up
  - Easy-to-use VPN apps for iOS, Android, MacOS, Windows, iPad, Linux, Apple
    TV, and Android TV
  - Our high-strength encryption provides a more secure connection than an internet proxy
  - Independently audited by third-party security experts
  - Trusted open-source code that anyone can review
  - Data protection using AES-256 and 4096 RSA encryption

  Join the privacy revolution

  Your support helps us bring online freedom to people around the globe. Join
  Proton today to protect yourself online and help create a secure, private,
  and free internet for everyone.

  Experts' opinion

  PCMag: "[Proton VPN's] is a slick VPN with an excellent collection of
  advanced features, and it has the best free subscription plan we've seen. Few
  competitors can match its mix of affordability, features, and design. For all
  that, it gets a rare five-star rating and earns our Editors' Choice award"

  Mozilla: "There are many VPN vendors out there, but not all of them are
  created equal. Proton VPN offers a secure, reliable, and easy-to-use VPN
  service and is operated by the makers of ProtonMail, a respected,
  privacy-oriented email service... As a company they have a track record of
  fighting for online privacy and they share our dedication to internet safety
  and security."

website: https://protonvpn.com
contact: https://github.com/pedro-avalos/protonvpn-snap/issues
issues: https://github.com/pedro-avalos/protonvpn-snap/issues
source-code: https://github.com/ProtonVPN/proton-vpn-gtk-app

base: core24
grade: devel
confinement: devmode
compression: lzo

platforms:
  amd64:

# TODO: Create app
#apps:
#  protonvpn:
#    command: usr/bin/protonvpn
#    desktop: snap/gui/protonvpn.desktop
#    extensions:
#      - gnome
#    plugs:
#      - desktop
#      - desktop-legacy
#      - wayland
#      - unity7
#      - x11
#      - network
#      - network-bind

parts:
  python-proton-core:
    plugin: python
    source-type: git
    source: https://github.com/ProtonVPN/python-proton-core.git

  python-proton-keyring-linux:
    plugin: python
    source-type: git
    source: https://github.com/ProtonVPN/python-proton-keyring-linux.git
    after:
      - python-proton-core

  python-proton-vpn-local-agent:
    plugin: python
    source-type: git
    source: https://github.com/ProtonVPN/python-proton-vpn-local-agent.git
    source-submodules: []
    after:
      - python-proton-core
      - python-proton-keyring-linux

  python-proton-vpn-api-core:
    plugin: python
    source-type: git
    source: https://github.com/ProtonVPN/python-proton-vpn-api-core.git
    source-submodules: []
    after:
      - python-proton-core
      - python-proton-keyring-linux
      - python-proton-vpn-local-agent

  python-proton-vpn-network-manager:
    plugin: python
    source-type: git
    source: https://github.com/ProtonVPN/python-proton-vpn-network-manager.git
    after:
      - python-proton-core
      - python-proton-keyring-linux
      - python-proton-vpn-local-agent
      - python-proton-vpn-api-core

  protonvpn:
    plugin: python
    source-type: git
    source: https://github.com/ProtonVPN/proton-vpn-gtk-app.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    source-submodules: []
    after:
      - python-proton-core
      - python-proton-keyring-linux
      - python-proton-vpn-local-agent
      - python-proton-vpn-api-core
      - python-proton-vpn-network-manager
